const express = require("express");

const router = express.Router();

/**
 * POST /api/export
 *
 * Accepts the full analysis result in the request body and returns
 * a Markdown document summarising the repository analysis.
 */
router.post("/", (req, res) => {
  const data = req.body;
  const languages = data.ext?.languages || data.languages;

  if (!data || !languages) {
    return res.status(400).json({ error: "Analysis data is required in the request body.", code: "MISSING_DATA" });
  }

  try {
    const md = generateMarkdown(data);
    const filename = (data.repoId || "codeatlas-export") + ".md";

    res.setHeader("Content-Type", "text/markdown; charset=utf-8");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.send(md);
  } catch (err) {
    res.status(500).json({ error: "Export failed", details: err.message });
  }
});

// ---------------------------------------------------------------------------
// Markdown Generator
// ---------------------------------------------------------------------------

function generateMarkdown(data) {
  const lines = [];
  const files = data.files || {};
  const types = data.type || {};
  const det = data.det || {};

  // Title
  const repoName = data.repo || "Repository";
  lines.push(`# CodeAtlas Report -- ${repoName}`);
  lines.push("");
  lines.push(`> Generated by [CodeAtlas](https://github.com/7sg56/CodeAtlas) on ${new Date().toISOString().split("T")[0]}`);
  lines.push("");

  // 1. Project Overview
  lines.push("## Project Overview");
  lines.push("");
  const frameworks = data.fw || [];
  if (frameworks.length > 0) lines.push(`**Frameworks:** ${frameworks.join(", ")}`);

  const stats = data.ss;
  if (stats) lines.push(`**Files:** ${stats.files}  |  **Folders:** ${stats.folders}`);

  const arch = data.arch;
  if (arch) {
    lines.push(`**Architecture Pattern:** ${arch.pattern}`);
    lines.push(`**Components:** ${arch.routers} Routers, ${arch.controllers} Controllers, ${arch.services} Services`);
  }
  lines.push("");

  // 2. Languages
  const languages = data.ext?.languages || [];
  if (languages.length > 0) {
    lines.push("## Languages");
    lines.push("");
    lines.push("| Language | Percentage |");
    lines.push("|----------|-----------|");
    for (const lang of languages) {
      lines.push(`| ${lang.language} | ${lang.percentage}% |`);
    }
    lines.push("");
  }

  // 3. Entrypoints
  if (data.entry && data.entry.length > 0) {
    lines.push("## Entrypoints");
    lines.push("");
    for (const id of data.entry) {
      lines.push(`- \`${files[id] || id}\``);
    }
    lines.push("");
  }

  // 4. API Surface
  if (data.api && data.api.length > 0) {
    lines.push("## API Surface");
    lines.push("");
    lines.push("| Method | Path | Handler |");
    lines.push("|--------|------|---------|");
    for (const [method, path, handler] of data.api) {
      const handlerLabel = files[handler] || handler;
      lines.push(`| \`${method}\` | \`${path}\` | \`${handlerLabel}\` |`);
    }
    lines.push("");
  }

  // 5. Architecture Summary
  if (arch) {
    lines.push("## Architecture Summary");
    lines.push("");
    lines.push(`The project follows a **${arch.pattern}** pattern with ${arch.modules} core functional modules.`);
    lines.push("");
  }

  // 6. Core Modules (Briefly)
  lines.push("## Core Modules");
  lines.push("");
  const modules = {};
  Object.keys(files).forEach(id => {
    const parts = files[id].split('/');
    if (parts.length > 1) {
      const mod = parts[0];
      modules[mod] = (modules[mod] || 0) + 1;
    }
  });
  Object.entries(modules).slice(0, 10).forEach(([mod, count]) => {
    lines.push(`- **${mod}**: ${count} source files`);
  });
  lines.push("");

  // 7. Architecture Anchors (Hubs)
  if (data.hubs && data.hubs.length > 0) {
    lines.push("## Architecture Anchors");
    lines.push("");
    lines.push("Primary dependency hubs in the repository:");
    lines.push("");
    for (const id of data.hubs) {
      lines.push(`- \`${files[id] || id}\` (${types[id]})`);
    }
    lines.push("");
  }

  // 8. Detailed File Analysis
  lines.push("## Detailed File Analysis");
  lines.push("");
  Object.keys(det).forEach(id => {
    const path = files[id] || `File ${id}`;
    const type = types[id] || "unknown";
    const d = det[id];

    // Skip generic components/styles in detailed analysis to save space
    if (type === 'component' || type === 'unknown') return;

    lines.push(`### \`${path}\` [${type.toUpperCase()}]`);
    if (d.fn && d.fn.length > 0) lines.push(`- **Functions:** ${d.fn.join(", ")}`);
    if (d.cx) lines.push(`- **Complexity:** ${d.cx}`);
    if (d.rt && d.rt.length > 0) {
      lines.push("- **Endpoints:**");
      for (const [m, p] of d.rt) lines.push(`  - \`${m} ${p}\``);
    }
    lines.push("");
  });

  lines.push("---");
  lines.push("*Generated by CodeAtlas High-Efficiency Engine*");
  lines.push("");
  
  // 9. Groq LLM Prompt (The "Secret Sauce")
  if (data.groqPrompt) {
    lines.push("## Groq LLM Prompt");
    lines.push("");
    lines.push("Copy and paste this JSON into a LLM (like Groq) to get an architectural overview of the repository:");
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(data.groqPrompt, null, 2));
    lines.push("```");
    lines.push("");
  }

  return lines.join("\n");
}

module.exports = router;
